# /Users/saschakohler/.config/tmuxinator/nlp-trainer.yml

name: nlp-trainer
root: /Users/saschakohler/Documents/01_Development/Active_Projects/nlp-trainer-app/

windows:
  - editor:
      layout: main-horizontal
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - nvim
        -
  - server:
  - logs:
